# Generated by Django 3.0.4 on 2020-06-16 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission', '0005_auto_20200616_1646'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportSignalSinistre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('gravite', models.CharField(choices=[('FAIBLE', 'FAIBLE'), ('MOYEN', 'MOYEN'), ('FORT', 'FORT'), ('CRITIQUE', 'CRITIQUE')], max_length=20)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Conducteur')),
                ('redacteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='RapportSignalProbleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('gravite', models.CharField(choices=[('FAIBLE', 'FAIBLE'), ('MOYEN', 'MOYEN'), ('FORT', 'FORT'), ('CRITIQUE', 'CRITIQUE')], max_length=20)),
                ('type_probleme', models.CharField(choices=[('PANNE', 'PANNE'), ('JCP', 'JCP')], max_length=30)),
                ('confirmed', models.BooleanField(default=False)),
                ('redacteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='RapportSignalChauffeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('gravite', models.CharField(choices=[('FAIBLE', 'FAIBLE'), ('MOYEN', 'MOYEN'), ('FORT', 'FORT'), ('CRITIQUE', 'CRITIQUE')], max_length=20)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Conducteur')),
                ('redacteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
