# Generated by Django 3.0.4 on 2020-07-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportsignalprobleme',
            name='confirmed',
            field=models.BooleanField(default=None),
        ),
    ]
