# Generated by Django 3.0.4 on 2020-07-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0002_auto_20200706_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportsignalprobleme',
            name='confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
