# Generated by Django 3.0.4 on 2020-06-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission', '0002_auto_20200616_0027'),
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Vehicule')),
                ('pieces', models.ManyToManyField(to='piece.Piece')),
            ],
        ),
    ]
