# Generated by Django 3.0.4 on 2020-06-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission', '0002_auto_20200616_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('reference', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date_aq', models.DateField(blank=True, null=True)),
                ('Nombre', models.PositiveIntegerField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Guide_personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, null=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piece.Piece')),
            ],
        ),
        migrations.CreateModel(
            name='Guide_constructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, null=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piece.Piece')),
            ],
        ),
    ]
