# Generated by Django 3.0.4 on 2020-06-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_auto_20200625_1554'),
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='piece',
            name='modele',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mission.Modele'),
            preserve_default=False,
        ),
    ]
