# Generated by Django 3.0.4 on 2020-06-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('grade', models.CharField(blank=True, max_length=30, null=True)),
                ('dateEmbauche', models.DateField(blank=True, null=True)),
                ('region', models.PositiveSmallIntegerField(choices=[(1, 'region-1'), (2, 'region-2'), (3, 'region-3'), (4, 'region-4'), (5, 'region-5'), (6, 'region-6')])),
                ('unite', models.CharField(blank=True, max_length=30, null=True)),
                ('service', models.CharField(blank=True, max_length=30, null=True)),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)], default=100)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_depart', models.CharField(max_length=30)),
                ('point_arrive', models.CharField(max_length=30)),
                ('dateMission', models.DateField()),
                ('distance', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('heureDepart', models.TimeField()),
                ('heureArrive', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculeInterne', models.CharField(blank=True, max_length=30, null=True)),
                ('matriculeExcterne', models.CharField(blank=True, max_length=30, null=True)),
                ('marque', models.CharField(blank=True, max_length=30, null=True)),
                ('kilometrage', models.IntegerField(blank=True, null=True)),
                ('modele_id', models.IntegerField(blank=True, null=True)),
                ('data_aq', models.DateField(blank=True, null=True)),
                ('region', models.PositiveSmallIntegerField(choices=[(1, 'region-1'), (2, 'region-2'), (3, 'region-3'), (4, 'region-4'), (5, 'region-5'), (6, 'region-6')])),
                ('unite', models.CharField(blank=True, max_length=30, null=True)),
                ('service', models.CharField(blank=True, max_length=30, null=True)),
                ('categorie', models.CharField(choices=[('A', 'Categorie A'), ('B', 'Categorie B'), ('C', 'Categorie C')], max_length=1)),
                ('etat', models.CharField(choices=[('HDS', 'HORS DE SERVICE'), ('MAUVAIS', 'MAUVAIS'), ('MOYEN', 'MOYEN'), ('BON', 'BON')], max_length=30)),
                ('dateProchaineRevision', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
