# Generated by Django 3.0.4 on 2020-06-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='data_aq',
            new_name='date_aq',
        ),
    ]
