# Generated by Django 3.0.4 on 2020-06-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20200616_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='conducteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mission.Conducteur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='vehicule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mission.Vehicule'),
            preserve_default=False,
        ),
    ]
