# Generated by Django 3.0.4 on 2020-06-16 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission', '0003_auto_20200616_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='redacteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
