# Generated by Django 3.0.4 on 2020-06-16 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_mission_redacteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='modele_id',
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('categorie', models.CharField(choices=[('A', 'Categorie A'), ('B', 'Categorie B'), ('C', 'Categorie C')], max_length=1)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Marque')),
            ],
        ),
        migrations.AddField(
            model_name='vehicule',
            name='modele',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mission.Modele'),
            preserve_default=False,
        ),
    ]
